name: Format code
on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  format-code:
    name: Format code
    runs-on: ubuntu-latest
    steps:
      - name: Checkout to branch
        uses: actions/checkout@v2

      - name: Format code
        id: check
        run: yarn install && yarn format-code

      - name: Create PR
        id: cpr
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.WORKFLOW_ACCESS }}
          commit-message: "chore: code files prettified"
          branch: code-styling
          delete-branch: true
          title: "chore: code files prettified"
          body: |
            ### Code files formatted using prettier style
            - related workflow file : [.github/workflows/prettier.yml](https://github.com/shamilkotta/offpitch_BackEnd/blob/main/.github/workflows/prettier.yml)
            - prettier config file : [.prettierrc](https://github.com/shamilkotta/offpitch_BackEnd/blob/main/.prettierrc)
          labels: code-styling
          assignees: shamilkotta
