name: Format code
on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  format-code:
    name: Format code
    runs-on: ubuntu-latest
    steps:
      - name: Checkout to branch
        uses: actions/checkout@v3

      - name: setup node env
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: install dependencies
        run: yarn install

      - name: run format
        run: yarn run format

      - name: Create PR
        id: cpr
        uses: peter-evans/create-pull-request@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "chore: code files prettified"
          branch: code-styling
          delete-branch: true
          title: "style: file formatted by prettier"
          body: |
            ### Code files formatted using prettier style
            - related workflow file : [.github/workflows/prettier.yml](https://github.com/shamilkotta/offpitch_BackEnd/blob/main/.github/workflows/prettier.yml)
            - prettier config file : [.prettierrc](https://github.com/shamilkotta/offpitch_BackEnd/blob/main/.prettierrc)
          labels: style
          assignees: shamilkotta
